version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"   # pprof
      - "8890:8890"   # Prometheus metrics do Collector
      - "8889:8889"   # Prometheus exporter (opcional)
      - "13133:13133" # Health check
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - otel-collector

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - otel-collector

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - ./elastic_templates:/usr/share/elasticsearch/config/templates
    networks:
      - otel-collector

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - otel-collector

  fastapi-app:
    build: ./fastapi-app
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
    depends_on:
      - otel-collector
    networks:
      - otel-collector

  # --- AQUI COMEÇA O STACK LARAVEL ---
  laravel_app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/logs/app:/var/log/app
    depends_on:
      - laravel_mysql
    networks:
      - otel-collector

  laravel_nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"       # Laravel acessível em http://localhost:8080
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/logs/nginx:/var/log/nginx
    depends_on:
      - laravel_app
    networks:
      - otel-collector

  laravel_mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - laravel_dbdata:/var/lib/mysql
    networks:
      - otel-collector

volumes:
  laravel_dbdata:

networks:
  otel-collector:
    name: otel-collector
    driver: bridge
